version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
  db:
    image: mysql:5.7
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
